### ISSUE TITLE
Use build args + customization

### ISSUE THREAD

**Issue by sem4phor** [BlackPepperSoftware/docker-craftcms#9]
Hello! (And sorry for opening another issue)

I wanted to set up a basic craft environment with a specified craft version (3.1.12) and some Customizations like described in the customization section of the README.

So a pretty similar setup to the provided demo with following Docker settings:

compose: 

```
version: '3'

services:
  site:
    build:
      context: .
      args:
        CRAFT_VERSION: 3.1
        CRAFT_BUILD: 12
    environment:
      DB_SERVER: database
      DB_USER: craft
      DB_PASSWORD: password
      DB_DATABASE: craft
      DB_DRIVER: mysql
      CRAFT_SITE_URL: http://localhost:8080/
    links:
      - database
    ports:
      - "8080:80"
  database:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: craft
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: craft
    ports:
      - "3306:3306"
``` 

Dockerfile:
```
ARG CRAFT_VERSION
ARG CRAFT_BUILD
FROM blackpepper/craftcms
COPY public /var/www/web
```

So the difference is that i use build args which i want to pass to the FROM base image of the dockerfile.
In the issue https://github.com/BlackPepperSoftware/docker-craftcms/issues/8 this worked because i didnt have a customized dockerfile instead i linked to your dockerfile directly via the context field in the compose file. SO setting build args worked.

Now i consume the your image via FROM in the dockerfile. This causes the build args from compose not being applied to your image. 
Do you have any idea how to pass/overwrite build args from compose to the FROM base image inside the Dockerfile? 

Kindly regards
